[features]
seeds = false
skip-lint = false
[programs.localnet]
cerkle = "3tLM17SwGY5ovjA5Kk7zge4odyAxaMpDdrXqR3XzSY5k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dhruvraj/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
